spring:
  env : dev
  datasource:
    url: jdbc:mysql://localhost:3306/easy?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1207808913@qq.com
    password: znvbcidqoeqaijjg #客户端授权码
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: true #可以任意
    properties.mail.display.sendname: false #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8
project:
  folder: ./file-storage

admin:
  emails: 1207808913@qq.com

# application.yml
qq:
  app:
    id: 123456
    key: 123456
  url:
    authorization: "https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s"
    access:
      token: "https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s"
    openid: "https://graph.qq.com/oauth2.0/me?access_token=%s"
    user:
      info: "https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s"
    redirect: "http://easypan.wuhancoder.com/qqlogincalback"